version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Build started"
  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync . s3://static-website-2005/ --delete

artifacts:
  files:
    - '**/*'
